<?php
require('config.php');
require('functions.inc.php');
unset($_SESSION['USER_LOGIN']);
unset($_SESSION['USER_ID']);
unset($_SESSION['USER_NAME']);
unset($_SESSION['LAST_ACTIVE_TIME']);
header('location:index.php');
die();
?>